---

- name: Add nginx.org signing key
  apt_key:
    data: "{{ lookup('file', 'nginx_signing.key') }}"
    state: present
  when: nginx_nginxorg_repo    

- name: Configure URL for nginx repository. 
  set_fact:
    repo_url: "{{ 'http://nginx.org/packages/' + ansible_distribution|lower + '/' 
      if not nginx_nginxorg_mainline else
      'http://nginx.org/packages/mainline/' + ansible_distribution|lower + '/' }}"

- name: Add nginx.org apt repository for {{ ansible_distribution_release }} 
  apt_repository:
    repo: "deb {{ repo_url }} {{ ansible_distribution_release }} nginx"
    state: present
  register: nginx_nginxorg_repo_added
  when: 
    - ansible_distribution_release in nginx_nginxorg_supported
    - nginx_nginxorg_repo

- name: Install nginx.
  apt: name=nginx state=present
  when:
    - (nginx_nginxorg_repo and nginx_nginxorg_repo_added) or 
      (not nginx_nginxorg_repo and not nginx_nginxorg_repo_added)

- name: Ensure nginx is running and will start on boot. 
  service: name=nginx state=started enabled=yes