---

- name: Add nginx.org signing key
  rpm_key:
    key: https://nginx.org/keys/nginx_signing.key
    state: present
  when: nginx_nginxorg_repo    

- name: Add nginx.org yum repository for {{ ansible_distribution }}/{{ ansible_distribution_major_version }} | STABLE
  yum_repository:
    name: nginx_stable
    description: "Latest stable version of nginx from nginx.org"
    enabled: "yes"
    gpgcheck: "yes"
    baseurl: http://nginx.org/packages/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/$basearch/
    state: present
  register: nginx_nginxorg_repo_added
  when: 
    - ansible_distribution_major_version in nginx_nginxorg_supported
    - nginx_nginxorg_repo
    - not nginx_nginxorg_mainline

- name: Add nginx.org yum repository for {{ ansible_distribution }}/{{ ansible_distribution_major_version }} cd | MAINLINE
  yum_repository:
    name: nginx_mainstream
    description: "Latest mainstream version of nginx from nginx.org"
    enabled: "yes"
    gpgcheck: "yes"
    baseurl: http://nginx.org/packages/{{ ansible_distribution | lower }}/{{ ansible_distribution_major_version }}/$basearch/
    state: present
  register: nginx_nginxorg_repo_added
  when: 
    - ansible_distribution_major_version in nginx_nginxorg_supported
    - nginx_nginxorg_repo
    - nginx_nginxorg_mainline

- name: Install nginx.
  yum: name=nginx state=present
  when:
    - (nginx_nginxorg_repo and nginx_nginxorg_repo_added) or 
      (not nginx_nginxorg_repo and not nginx_nginxorg_repo_added)

- name: Ensure nginx is running and will start on boot. 
  service: name=nginx state=started enabled=yes