---

# Set these variables if you wish to use the upstream nginx.org repositories. 
# Leave them disabled to use distribution supplied nginx. use_nginx_mainline 
# will have no effect without use_nginx_repo. 
nginx_upstream_repo: no
nginx_mainline: no

# Variables used in top level nginx.conf and filesystem configuration. 
nginx_conf_root: /etc/nginx
nginx_sites_enabled: "{{ nginx_conf_root }}/sites-enabled" 
nginx_sites_available: "{{ nginx_conf_root }}/sites-available" 
nginx_worker_processes: "1"
nginx_error_log: /var/log/nginx/error.log
nginx_error_log_level: warn
nginx_pid: /var/run/nginx.pid
nginx_worker_connections: 1024
nginx_default_type: application/octet-stream
nginx_log_format_name: main
nginx_log_format: | 
 '$remote_addr - $remote_user [$time_local] "$request" '
 '$status $body_bytes_sent "$http_referer" '
 '"$http_user_agent" "$http_x_forwarded_for"'
nginx_access_log: /var/log/nginx/access.log
nginx_access_log_format: main
nginx_sendfile: "on"
nginx_tcp_nopush: "off"
nginx_keepalive_timeout: 65
nginx_gzip: "off"

#nginx_upstream_servers:
#  - server:
#      file_name: "django-upstream.conf"
#      upstream: {name: "django", type: "server", destination: "127.0.0.1:1111"}

nginx_sites:
  - server:
      file_name: ansible-default.conf
      listen: 80
      server_name: localhost
      root: "/var/www/ansible-default"
#      locations1: {name: "/", uwsgi_pass: "django", include: "uwsgi_params"}
#      locations2: {name: "/static/", alias: "/var/www/static"}
#      locations3: {name: "/media/", alias: "/var/www/media"}
